### ISSUE TITLE
Error in asyncio

### ISSUE THREAD

**Issue by forexhill** [wardbradt/peregrine#16]
Hi! Thank you for creating this. I am trying the following;

```
~/peregrine $ python ./examples/multiple_coins_one_exchange.py
Traceback (most recent call last):
  File "./examples/multiple_coins_one_exchange.py", line 1, in <module>
    import asyncio
  File "/usr/local/lib/python2.7/dist-packages/asyncio/__init__.py", line 9, in <module>
    from . import selectors
  File "/usr/local/lib/python2.7/dist-packages/asyncio/selectors.py", line 39
    "{!r}".format(fileobj)) from None
                               ^
SyntaxError: invalid syntax
```

Any idea what may be going wrong here? The asyncio lib was installed with pip install.

**Comment by wardbradt** [comment]
No idea, this seems to be an asyncio, not peregrine error.

**Comment by twelvearrays** [comment]
asyncio is only for Python 3
