### ISSUE TITLE
Order_book

### ISSUE THREAD

**Issue by shivamgoyal1** [wardbradt/peregrine#29]
```Task exception was never retrieved
future: <Task finished coro=<_add_weighted_edge_to_graph() done, defined at /Users/shivamgoyal/bitcoin_arb/preregine/peregrine/peregrinearb/utils/single_exchange.py:95> exception=UnboundLocalError("local variable 'order_book' referenced before assignment",)>
Traceback (most recent call last):
  File "/Users/shivamgoyal/bitcoin_arb/preregine/peregrine/peregrinearb/utils/single_exchange.py", line 115, in _add_weighted_edge_to_graph
    ticker_bid = order_book['bids'][0][0]
UnboundLocalError: local variable 'order_book' referenced before assignment
Task exception was never retrieved
future: <Task finished coro=<_add_weighted_edge_to_graph() done, defined at /Users/shivamgoyal/bitcoin_arb/preregine/peregrine/peregrinearb/utils/single_exchange.py:95> exception=UnboundLocalError("local variable 'order_book' referenced before assignment",)>
Traceback (most recent call last):
  File "/Users/shivamgoyal/bitcoin_arb/preregine/peregrine/peregrinearb/utils/single_exchange.py", line 115, in _add_weighted_edge_to_graph
    ticker_bid = order_book['bids'][0][0]
UnboundLocalError: local variable 'order_book' referenced before assignment
Task exception was never retrieved
future: <Task finished coro=<_add_weighted_edge_to_graph() done, defined at /Users/shivamgoyal/bitcoin_arb/preregine/peregrine/peregrinearb/utils/single_exchange.py:95> exception=UnboundLocalError("local variable 'order_book' referenced before assignment",)>```


The program I'm running is: 
```import asyncio
from peregrinearb import load_exchange_graph, print_profit_opportunity_for_path, bellman_ford


loop = asyncio.get_event_loop()
graph = loop.run_until_complete(load_exchange_graph('binance'))

paths = bellman_ford(graph, 'BTC', unique_paths=True)
for path in paths:
    print_profit_opportunity_for_path(graph, path)```

**Comment by wardbradt** [comment]
This has been fixed.
https://github.com/wardbradt/peregrine/pull/30
