### ISSUE TITLE
No such file or directory issue

### ISSUE THREAD

**Issue by guldam** [wardbradt/peregrine#35]
when I run

>>> from peregrinearb import get_opportunity_for_market
>>> import asyncio
>>> opportunity = asyncio.get_event_loop().run_until_complete(get_opportunity_for_market('BTC/USD'))

I receive

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.6/site-packages/peregrinearb/async_find_opportunities.py", line 61, in get_opportunity_for_market
    finder = OpportunityFinder(ticker, exchanges=exchanges, name=name)
  File "/usr/local/lib/python3.6/site-packages/peregrinearb/async_find_opportunities.py", line 16, in __init__
    exchanges = get_exchanges_for_market(market_name)
  File "/usr/local/lib/python3.6/site-packages/peregrinearb/utils/general.py", line 24, in get_exchanges_for_market
    with open('./../peregrinearb/collections/collections.json') as f:
FileNotFoundError: [Errno 2] No such file or directory: './../peregrinearb/collections/collections.json'

What should I do?
I Installed all the modules peregrinearb required.

**Comment by wardbradt** [comment]
Hi, I will look into fixing this. I know the cause right now. 

For future reference, could you please submit Python errors as preformatted text? It makes them much easier to read and avoids markdown errors (such as \_\_init\_\_ becoming a bold __init__)

**Comment by wardbradt** [comment]
This has been fixed. See: https://github.com/wardbradt/peregrine/commit/2673acfff417ec8bf1cb970a5a645fea339e76de
