### ISSUE TITLE
Having issues installing

### ISSUE THREAD

**Issue by shivamgoyal01** [wardbradt/peregrine#51]
Hi, I'm running the example code and getting this error:

```Users-MacBook-Pro-2:examples User$ python multiple_coins_multiple_exchanges.py 
Traceback (most recent call last):
  File "multiple_coins_multiple_exchanges.py", line 1, in <module>
    from peregrinearb import create_weighted_multi_exchange_digraph, bellman_ford_multi, \
  File "/Library/Python/2.7/site-packages/peregrinearb/__init__.py", line 1, in <module>
    from .async_find_opportunities import *
  File "/Library/Python/2.7/site-packages/peregrinearb/async_find_opportunities.py", line 31
    async def _test_bid_and_ask(self, exchange):
            ^
SyntaxError: invalid syntax```

**Comment by teodoryantcheff** [comment]
You need python 3 for this syntax to work.
