### ISSUE TITLE
AttributeError: module 'ccxt.async_support' has no attribute '/'

### ISSUE THREAD

**Issue by ibnachraf** [wardbradt/peregrine#64]
Hello,

Thank you for this very useful application.
But i have some issues when running,
here is my stack trace:

"C:\Users\NV Master\AppData\Local\Programs\Python\Python36\python.exe" "C:/Users/NV Master/Documents/arbitrage/peregrine-master/peregrine-master/examples/example.py"
Traceback (most recent call last):
  File "C:/Users/NV Master/Documents/arbitrage/peregrine-master/peregrine-master/examples/example.py", line 5, in <module>
    opportunity = asyncio.get_event_loop().run_until_complete(get_opportunity_for_market("BTC/USD", collections_dir))
  File "C:\Users\NV Master\AppData\Local\Programs\Python\Python36\lib\asyncio\base_events.py", line 466, in run_until_complete
    return future.result()
  File "C:\Users\NV Master\Documents\arbitrage\peregrine-master\peregrine-master\peregrinearb\async_find_opportunities.py", line 324, in get_opportunity_for_market
    finder = OpportunityFinder(ticker, exchanges=exchanges, name=name)
  File "C:\Users\NV Master\Documents\arbitrage\peregrine-master\peregrine-master\peregrinearb\async_find_opportunities.py", line 52, in __init__
    exchanges = [getattr(ccxt, exchange_id)() for exchange_id in exchanges]
  File "C:\Users\NV Master\Documents\arbitrage\peregrine-master\peregrine-master\peregrinearb\async_find_opportunities.py", line 52, in <listcomp>
    exchanges = [getattr(ccxt, exchange_id)() for exchange_id in exchanges]
AttributeError: module 'ccxt.async_support' has no attribute '/'

for this example:

from peregrinearb import get_opportunity_for_market
import asyncio

collections_dir = '/Users/wardbradt/cs/peregrine/'
opportunity = asyncio.get_event_loop().run_until_complete(get_opportunity_for_market("BTC/USD", collections_dir))
print(opportunity)

what refer to **collections_dir** ?
Otherwise other examples in the project are working fine.

thanks for your help.

**Comment by wardbradt** [comment]
Thank you for pointing this out. This is an outdated example, which I will fix. You should not pass `collections_dir` to `get_opportunity_for_market`. So the correct code would be:
```
from peregrinearb import get_opportunity_for_market
import asyncio

collections_dir = '/Users/wardbradt/cs/peregrine/'
opportunity = asyncio.get_event_loop().run_until_complete(get_opportunity_for_market("BTC/USD", collections_dir))
print(opportunity)
```
However, I think there are some other issues impeding this snippet from running successfully. I will fix them.

**Comment by Shubham1605** [comment]
In the response that you have mentioned as resolution to what refer to collections_dir ? collections_dir is still being passed.Can you please tell what should be value of collections_dir ?

**Comment by sword134** [comment]
I've got the exact same issue. @wardbradt fix didn't work for me

**Comment by alvedys** [comment]
hello friends, did any of you get the solution?

**Comment by massb** [comment]
Hello guys

I have the same issue. @wardbradt fix is actually the same as the original example.

Please help :D

**Comment by pratyushv9** [comment]
Hi everybody, any updates on how to fix it?

**Comment by alvedys** [comment]
any solution of this error??

**Comment by pratyushv9** [comment]
@alvedys Well you can try switching to the 'working' branch and execute the example without the collections_dir parameter as the author has mentioned. But I am still getting errors for the other examples

**Comment by dkjhaj2ee** [comment]
@wardbradt I am facing this issue, can we get solution for this?
```
AttributeError: module 'ccxt.async_support' has no attribute '/'
```

**Comment by tomekozlowski** [comment]
same issue here
